name: Loader Getter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu:20.04

    # strategy:
    #   matrix:
    #     node-version: [20.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: ls -la /usr/lib/